CREATE TABLE IF NOT EXISTS new_news (
    new_id INT AUTO_INCREMENT PRIMARY KEY,
    new_nick VARCHAR(50) NOT NULL,
    new_message VARCHAR(1024) NOT NULL,
    new_image VARCHAR(200),
    new_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;